### ISSUE TITLE
Login server info per account?

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#114]
So I noticed after logging in about 15 accounts.  If the same server is used in a short period (within a few hours).  I get a network error from the server and for me to check my "firewall settings".  This is basically just a cooldown from being able to login a bunch of times.  It clears up after a while, but I noticed if I switch servers I can login right away again.  The problem is I have no clue what server my accounts used to login for the first 15.  So I was thinking if it would be possible to display the login server IP in use on the account that were already logged in.  Like mousing over on the running account on LB and it would display it in the tooltip window?

**Comment by KairuByte** [comment]
o.0 I have never encountered this. Out of curiosity, what area of the world are you located in? I'm wondering if they have some sort of regional settings...

**Comment by TheCheatsrichter** [comment]
This would require Launchbuddy to actually monitor the network traffic of the Gw2 client, which I don't see as a very good idea.

Another idea (which I am more of a fan of)would be to force Launchbuddy itself to choose the Login and asset server for you even if you don't choose it manualy. This way we always know which account is using which server, because the command line argument forces the client to use it.
