### ISSUE TITLE
Injected software isn't working properly

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [TheCheatsrichter/Gw2_Launchbuddy#118]
I can get GW2Hook to load, but ArcDPS isn't loading at all.

Not sure what I'm doing wrong.

**Comment by SaiyanOfDarkness** [comment]
Doing everything I can to try to get it to work.. even just running d3d9.dll in the injector section.. it's not loading at all.

**Comment by SaiyanOfDarkness** [comment]
So clearing 200 cache folders helped a little, but build templates nor extras for arcdps load no matter what I do.  I can load the game normally with them in bin64, but they refuse to load with 1.8.9

**Comment by KairuByte** [comment]
I'm not at all familiar with the inner workings of ArcDPS, so this may be a question better suited to that particular dev, however if I were to take a guess... Remove either d3d9_chainload.dll (less likely to work) or follow normal ArcDPS chainload configuration and only load d3d9_chainload.dll.

What I assume is happening is one of two things:
- chainload is looking for arcdps but not finding it because it is not named as expected.
- chainload is loading arcdps and/or plugins, but so is LB causing a conflict and both instances to cancel themselves.
