### ISSUE TITLE
Addon function

### ISSUE THREAD

**Issue by Siofral** [TheCheatsrichter/Gw2_Launchbuddy#133]
I have Gw2TacO as an addon. It will kick on for the first login (I seldom use more than one account at a time). It will not kick on for anything past the first login.

To be clear . . . I log into my first account and TacO launches. I log out of my first account and log into my second. TacO does not launch. I have to launch it manually with administrative privileges to get it to launch.

**Comment by Canyonbydesign** [comment]
I was actually having this same issue and did some digging. You have the "Close when GW2 quits" setting checked. So you launch Taco when you open launchbuddy, then are closing it when you close your first gw2 client. It doesnt relaunch because it actually is being launched when you first open launchbuddy not when you launch an account. 

If you uncheck that setting it should fix your problem.
