### ISSUE TITLE
Virus/loading screen/delete

### ISSUE THREAD

**Issue by Grimleiv** [TheCheatsrichter/Gw2_Launchbuddy#164]
Latest version delete it self.. and all info. Virus or intended?

Also prew version 2.1.1 the loading screen in same cases go over 1 minuter, Somtimes 30+ seconds. If I start GW2 normal it takes 8 to 12 seconds. Any solution for this :)

Grim

**Comment by SaiyanOfDarkness** [comment]
There was a bug with -maploadinfo causing long loading times.  If you have that enabled in LB.. it might be why.  Also 2.1.2 puts out a fake virus alert, I believe because of its interactions with other folders on your PC (like appdata, etc).  If you have the option to turn off or set it to ignore the file.. it should work like normal.
