### ISSUE TITLE
after one account opens, it refuses to start others.

### ISSUE THREAD

**Issue by GW2Steph** [TheCheatsrichter/Gw2_Launchbuddy#174]
When i click to open all 3 accounts, and then click launch, only the first account on the list gets launched, the rest end up in a cycle of 
![0bfbb44fbb5b01221046125339a6e96e](https://user-images.githubusercontent.com/65006449/81375542-a81dc080-90f9-11ea-84c9-3eced8def577.png)

**Comment by DoodleSchrank** [comment]
I have the same issue.
For me it generally happens when I try to launch a seconds instance.

**Comment by Djnm** [comment]
Me too
it's been several weeks now that I have this same problem impossible to launch another instnace at the same time

**Comment by kevklam** [comment]
I don't know what triggers this for me, but every so often it starts happening. I can tell when it's about to mess up because when launching the first account, it logs in but then doesn't automatically hit 'play' like it usually does. Rebooting (or just logging out of Windows and re-logging in) seems to fix the issue temporarily.

I've tried reproducing the problem by opening multiple instances of launchbuddy, running various apps as admin, running gw2 manually alongside launchbuddy etc. but nothing seems to trigger it except for randomly after a while it starts to happen.
