### ISSUE TITLE
Suggestion - Restore previous graphics-configuration after all Launchbuddy managed game-windows have been closed

### ISSUE THREAD

**Issue by its-felix** [TheCheatsrichter/Gw2_Launchbuddy#216]
I have 2 seperate installtions of GW2. One, without any addons, for my alts which I login using LB. The other one using some addons which I use for my main account. I launch my main account using the vanilla-launcher. Since the graphics configuration file is not relative to the installation path, I end up with my alt-account graphics configuration when re-logging my main after I'm finished with my alts.

My suggestion: Copy the graphics configuration before the first LB-Managed instance is started. Restore this graphics configuration after the last LB-Managed instance closes.

**Comment by TheCheatsrichter** [comment]
Launchbuddy allready does this to some degree. 
1. It does make a backup from the "default" settings
2. Copy account linked GFX file to the according place
3. Launch the game client
4. Wait for the Gfx file to be loaded in
5. Restore default settings

Now the problem is that Gw2 itself overwrites the the graphics config. Which in that case could overwrite the default setting.
This could be fixed if the GFXManager was updated to always keep the backup and copy it back in when either LB closes or the last running client was closed.

**Comment by codeflush-dev** [comment]
Hey, thanks for your reply!
Currently, I start LB using this simple batch Script:
```batch
copy /y /b "C:\Users\felix\AppData\Roaming\Guild Wars 2\GFXSettings.Gw2-64.exe.xml" "C:\Users\felix\AppData\Roaming\Guild Wars 2\GFXSettings.Gw2-64.exe.xml.temp"
start /wait "" "%~dp0Gw2.Launchbuddy.exe"
move /y "C:\Users\felix\AppData\Roaming\Guild Wars 2\GFXSettings.Gw2-64.exe.xml.temp" "C:\Users\felix\AppData\Roaming\Guild Wars 2\GFXSettings.Gw2-64.exe.xml"
```

Which does the job for me. However, it would be nice-to-have this feature built-in of course.
