### ISSUE TITLE
Launchbuddy not saving in-game settings

### ISSUE THREAD

**Issue by Andreychik32** [TheCheatsrichter/Gw2_Launchbuddy#222]
Hi! Since last update, Launchbuddy stopped saving in-game graphics and sound settings for my accounts.

**Steps to reproduce:**

1. Launch saved account in launchbuddy v2.3.1;
2. Change sound settings as you like;
3. Close game;
4. Start the same account in launchbuddy;
5. Check your sound settings and see that they weren't saved.

I use the latest _clean_ Windows 10 (build 19042.867). Only things that I've installed is GW2 (with d912pxy and gw2radial), Launchbuddy, drivers and some other non-intrusive things like discord etc.

I can't remember if that issue was in the previous version of launchbuddy.

**Comment by TheCheatsrichter** [comment]
Some settings like the sound volume are not saved in the GFX file of gw2. Therefore they are saved in the local.dat file. Now we have following problem: when we launch multiple accounts we have to swap out the mentioned local.dat file in order to make the login work. This has the bitter side effect that settings like volume can't be saved to the specific local.dat file that easily.

Why some settings are in a seperate GFX file and others are saved in the local.dat file is beyond my knowledge.

**Comment by TheNasbit** [comment]
@Andreychik32 
Look at my comment on another issue (#228): https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/228#issuecomment-835230410

It's the same as interface-size (and other local settings), you can set it - but you have to do it before setting the Loginfile in Launchbuddy.

Launchbuddy cannot access settings stored inside the Local.dat, it could otherwise also read/write stored Login-Credentials. So you have to do this "workaround"
