### ISSUE TITLE
How is the Plug-Ins tab meant to be used?

### ISSUE THREAD

**Issue by KOVIKO** [TheCheatsrichter/Gw2_Launchbuddy#226]
Everything else in LaunchBuddy makes sense from what I can see. I put YoloMouse in the Addons tab, the TacO/BlishHUD tab expects the executables for TacO and/or Blish HUD, etc. But the Plugins tab, I'm not so sure.

I see that it expects DLL files and has a checkbox to autoupdate plugins, so I checked to see if I could add the `d3d9.dll` file from [GW2Radial](https://github.com/Friendly0Fire/GW2Radial) to it so I could potentially stop using [GW2 Addon Manager](https://github.com/fmmmlee/GW2-Addon-Manager) to handle the management of DLL injectors for GW2. However, attempting to addon that DLL file to the Plugins tab results in the error:

`Could not load plugin from path/to/plugin/plugin.dll`
![image](https://user-images.githubusercontent.com/835767/115162923-476e6600-a074-11eb-9255-584e9191e45d.png)

Am I not understanding what counts as a plugin? Are there any examples of plugins that I can use?

**Comment by CamdenQ** [comment]
I am having this same issue. Neither GW2Radial nor ArcDPS, both fresh downloads, will open. 

Since there is absolutely no documentation on how to use this app, just a link to Tekkit's "quick guide" video which doesn't go into real detail about things like this, I have no idea if this is actually an issue or just user error.
