### ISSUE TITLE
Overlay size setting

### ISSUE THREAD

**Issue by Kundy13** [TheCheatsrichter/Gw2_Launchbuddy#228]
Thank you for making Launchbuddy, it's awesome!
The one thing I miss is an option to launch the game with the setting to set the overlay size to small instead of normal. Is there a command for that?

**Comment by TheNasbit** [comment]
@Kundy13 
Interface-Size or Audio-Settings are saved within the Local.dat - where the login credentials are saved. (Along with some other local settings). So Launchbuddy cannot access these settings directly. (Otherwise, it could also read/write login credentials)
So you "set" these settings when creating your Loginfile. You can start gw2 w/o Launchbuddy set all settings u want (like volume, interface-size, ...). Then go to Account Settings in Launchbuddy and do "Set Loginfile" - the file will based on the existing Local.dat, containing the settings you want.
These Settings will always apply when starting this account - so if you change things like Volume/Interface Size afterward, it will not be permanent and will be overwritten on the next startup.

It is not ideal, but that way you can change settings for your accounts. Since the change for autologin, I do this for the volume settings.
