### ISSUE TITLE
Problem injecting both ArcDPS and GW2Radial dll's using Launchbuddy

### ISSUE THREAD

**Issue by KaptainO** [TheCheatsrichter/Gw2_Launchbuddy#245]
This is probably user error but I have tried following the instructions and videos on how to do this and not getting anywhere.

I want to use both ArcDPS and GW2Radial addons. If I put only one of them in the Injected Software section then it works, but when I put both in there only GW2Radial works.

My understanding is that with Launchbuddy I don't have to do any renaming of the dll for chainloading, am I mistaken?

This is a screencap of the Launchbuddy Account Setting Window
![image](https://user-images.githubusercontent.com/48570040/121024510-49020380-c772-11eb-9976-9442e9455a46.png)
When I launch that account I can hit Shift+Alt+M to open the GW2Radial menu but Shift+Alt+T does not open the ArcDPS menu.

If you need any additional info from me please let me know!

Thank you for all your work on Launchbuddy!

**Comment by KaptainO** [comment]
Just an update on my situation. After the most recent update to the game client now if I try to launch with both dll listed in the injected software tab arcdps does work, unfortunately gw2radial does not. Both addons work separately if I only put the one dll in the tab, but I can't get both to run at the same time.

I realise this is a problem involving addons created by other people but it *seems* like they work by themselves and it is the launchbuddy functionality that isn't working for me. If this question does not belong here or you are not interested in fixing it just let me know.

Thanks again for your work creating and maintaining Launchbuddy!

**Comment by KaptainO** [comment]
Another update. It seems like whichever addon I add the dll for first works and the one I add second doesn't.

Does anyone here have 2 different dll's injected using Launchbuddy? Is there something I am doing wrong?

It looks like someone commented on Tekkit's recent Launchbuddy youtube video with the same (or a similar) problem.

**Comment by TheCheatsrichter** [comment]
Support for third party software is kind of hard as these addons were never programmed to work flawlessly with multiple gameclients. And yes you are doing everything correct, renaming of the dlls is not needed.
Therefore it is not possible for me to pinpoint where this issue is comming from. It is likely some sort of collision as these addons work in a similar way.

Do they work when you only run one addon at a time?

**Comment by Snaid1** [comment]
I'm having the same problem. it seems that Launchbuddy only launches the last dll of any given name. It also won't load several addons if they have names other than "d3d9.dll". 

Examples:
- I have a configuration like KaptainO shows in his screenshot. only ArcDPS loads for me. 
- I swap which one is first in the list. now the other Addon loads.
- I rename GW2Radial's dll to be "d3d9_chainload.dll". GW2Radial does not load when I start the profile, even if it is the only addon in the injected software list. 
- if I only use 1 addon with the name "d3d9.dll" it loads fine. it also works fine with Reshade and/or GW2Hook since those have other names. 
- Arcdps, GW2Radial, d912pxy all seem to only be loaded by launchbuddy when launching a profile if they are named d3d9.dll. if I give another name (such as "d912pxy.dll") it does not load when the game starts
- Reshade 4.9 and GW2Hook seem to work fine if named "dxgi.dll" or "Reshade64.dll" not sure about other names.
- all behaviors listed above are seen when loading a single profile.

Related Multiboxing issue:
- if a dll addon is put in the bin64 folder, it only loads for some of the profiles when multiboxing (sometimes only the first one). This bug would not matter if the above issues with injected software is solved. 

@KaptainO 
For a workaround for ArcDPS and Gw2Radial I cheated and put the Radial DLL in the bin64 folder with the name "d3d9_chainload.dll" and it loads whenever one of my profiles in LaunchBuddy loads arcdps. May have issues with only some profiles loading it while multiboxing. YMMV. good luck.

**Comment by unrelentingsarcasm** [comment]
Similar to everyone else's problem, mine seems to be relegated to GW2Radial specifically.  It does not matter what it is named, or where it lives on my PC.  It will not work for me without uninstalling ArcDPS.  I currently run ArcDPS renamed as d3d9.dll and placed in my bin64 folder.  I also have d912pxy.dll in my bin64 folder and GW2 Hook as ReShade64.dll in my bin64 folder as well.  All of them work, but GW2Radial won't work as d3d9_chainload.dll in the bin64 folder, as d3d9.dll in another folder, or as GW2Radial in any folder.   The creator of GW2Radial advertises her software as working well with Addon Manager and she gets numerous issue posts about it not working with Launch Buddy.  Would be great if the two creators of LB and Radial could work together to resolve this issue so we're not limited on the other addons (i.e., GW2 Hook), which Addon Manager does not support.

**Comment by Snaid1** [comment]
So just as a potential workaround. I tried clearing my addons folder and installing them fresh using the [GW2-UOAOM](https://github.com/fmmmlee/GW2-Addon-Manager) and now both arcdps and gw2radial work loaded through that even though neither is named d3d9.dll. I am having a problem in that while those 2 play nice, using reshade or GW2hook with the addons installed by GW2-UOAOM causes the other addons not to work. So if you aren't using GW2hook or Reshade then this could be a solution for you.
