### ISSUE TITLE
Client Retry

### ISSUE THREAD

**Issue by Geebbo** [TheCheatsrichter/Gw2_Launchbuddy#251]
Keep getting an issue, cant open more than one account at once.

![image](https://user-images.githubusercontent.com/86951025/124436344-33a3e780-ddb9-11eb-8afc-8fc282c41707.png)

**Comment by TheWhiteWolves** [comment]
I've been getting the same since updating to v2.4.0, I've had to revert back to v2.3.9 to make it work again

**Comment by TheCheatsrichter** [comment]
Just to clarify this issue wasd reported back with 2.3.9.
Can you please provide some more info?

Is this only on the second account?
Does only one specific account not work?
Can you please try to add an account without loginfile and launch it as the seocnd account?

**Comment by TheWhiteWolves** [comment]
Had a play around with a few different scenarios and versions and seems like if you launch 1 account its fine most of the time, though occasionally LB goes into a locked up state waiting.

If you try to run more than one account thats when you really notice it as it'll either completely lock up until it craps out or if the automated login gets the press the login button it will launch the 2nd account before then crapping out because it didnt get focus to press the buttons itself.

had a very quick scan through some of the related code areas and its possible its getting hung up somewhere in the while loop on line 597 of the client manager trying to get itself to the running state, thus why it locks up.

https://github.com/TheCheatsrichter/Gw2_Launchbuddy/blob/17aaaa3ddb2ae5425f964985ba5fdf448c20b16e/Gw2%20Launchbuddy/ObjectManagers/ClientManager.cs#L597

**Comment by TheWhiteWolves** [comment]
I think I might have found a clue to what's happening, when you try to open any account after the first one, it keeps focusing everything on the first instance instead of the a second instance.

You can see this best if you first launch 1 account and get it all running then attempt to launch a second one (this used to work fine and run the second instance), what it does is latch onto the first instance and in my case resize my window, etc instead of launching the second one, before eventually stopping and saying it crashed and couldn't load

**Comment by TheWhiteWolves** [comment]
Some further investigation and notes regarding the few times I've managed to get it to open more than 1 account at a time, it looks like the reason it is occasionally able to open a 2nd and very rarely 3rd account is because in the couple second gap between hitting PLAY on the login window and the actual game window appearing, there is no existing instance for it to latch onto and thus allows it to open the next instance at which point when it comes to the 3rd attempt it latches onto that 1st instance instead of creating a new one.

**Comment by TheCheatsrichter** [comment]
I am currently writting some additional code to further test this. I am currently busy getting the antivirus flags away. So my focus will come back to this when the false positives are gone

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/261

closign this issue and merge with new issue
