### ISSUE TITLE
Mouse Profile doesn't work with LaunchBuddy

### ISSUE THREAD

**Issue by Zaidya** [TheCheatsrichter/Gw2_Launchbuddy#267]
Hello,

I use a Logitech G600 Gaming Mouse with the newest software from Logitech. It has Gameprofiles on it and I have a special one for GW2. When I start GW2 without LaunchBuddy my Gamingprofile works just fine.
When I start LaunchBuddy it also switches to the Gameprofile, so the Logitech software knows, that I am playing GW2, but the Keybindings don't work at all.
I also already made a fix profile for everything, but it doesn't work with this one either. 
A week ago when I last played, everything worked just fine.
Anyone knows what I do wrong, or on wich side the bug may be?

**Comment by nevertrustacat** [comment]
Same issue, also with a Logitech mouse, but an old one, that uses Set Point software. I've globally bound * and / to the side buttons that I've bound in-game to auto-attack and mount/demount. Both buttons don't work in the game when launched with Launchbuddy. Work fine otherwise. 

I don't use profiles, those are globally bound keys.
