### ISSUE TITLE
after a few logins i get error msgs

### ISSUE THREAD

**Issue by GotNoSkill** [TheCheatsrichter/Gw2_Launchbuddy#268]
After a few logins i get (The game client is unable to gain access to the log-in server at this time. This is most commonly caused by firewall or router settings, security applications, or connecting through a campus network)    or it just says   [[ undefined ]]   error msgs and doesnt log me into my accounts and i  try to put the username  ect in and it still gives the error msgs it works until i log into the like 6th account+ and stops me from login in completely till it randomly goes away   any fixes?

**Comment by zW-iwnl** [comment]
I got same problem here, I can log in only two accounts in same time and other accounts drop to same error. I tried many things and nothing worked for me.

**Comment by WindowsMe2** [comment]
It's semi related to GW2 Launchbuddy in combination with 2FA, I think. Whenever my network changes GW2 launchbuddy manages to trigger 2 FA requests which result in 2 SMS that I receive. After a few accounts the rest of them get locked out. I asked A.Net support about it and they told me, they've locked access to the accounts (for 24hrs) because of too many password request attempts ( I assume FA requests count as well). Since I have 14 alt accounts running all on the same 2FA number, I trigger it pretty fast. 
It's annoying but I'm not sure if fixing the double request would solve the issue completely.

**Comment by CerberusKCO** [comment]
I got the same issue, as a person who have 40+alts account i can"t log them in the same hour.
The first 20 accounts doesnt get any issue, but afterwards i get the same error message, so i need to wait 3 or 4 hours then i can open the rest without problem.
it's a pain and would be good to be fixed =)

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/268

Gonna close this issue and merge with newer issue.
