### ISSUE TITLE
A log in delay timer would be useful.

### ISSUE THREAD

**Issue by GabrielB-Norway** [TheCheatsrichter/Gw2_Launchbuddy#287]
I have 25 GW2 accounts and when logging on to multiple accounts it usually stops working after the 5th or 6th account is launched in succession. I notice that this always seems to happen for the same reason, namely because the accounts launch too quickly. 

So the 6th account starts logging in, before the 5th has finished starting the game. Which seems to create some kind of conflict with the log in files. 

I'm fairly certain that a setting which allows users to set a time delay between account launches would solve this. For instance adding anywhere between 1 and 9 seconds.

**Comment by aEtherEater** [comment]
I run into this issue as well. 25 accounts and have to do a few at a time or it out runs the launcher on an SDD.
I've also run into login server issues but that is not related to LB. That is Anet not wanting more than two simultaneous connections per IP after 10-13. I've gotten around this by logging into a character.
A delay that is configurable in LB would fix this for me. 20-30 seconds would work as that would provide enough time for the client to login (takes about 3-6 seconds after 15 accounts have logged in) and another 15-20 for the client to load including to character.

**Comment by ScrambledBrain** [comment]
I also would like to have an adjustable delay timer for each account which add a sleep timer after account is started.

This sleep timer should also be used to wait, before enabled addons auto-load after starting the account.
Or addons should be generally loaded, if the account start sequence is finished.

My computer is not a new one and each account start from older SSD and the slow CPU take some time to start GW2 properly.
And if this is not fast enough, TacO starts and simply closes afterwards, because GW2 is not yet completely loaded.
Additionally/Alternatively TheCheatsrichter could also add some small buttons to the account picker overlay, where addons could be started, insted of the need to go back to the GW2LB interface.

@TheCheatsrichter : It would be nice, if you can find a little time to implement some of this =) Especially a sleep timer should be made quite easy ;D

Summary of ideas:
- add an adjustable sleep timer for each account after start of it
- the sleep timer should be used to delay next account start
- the sleep timer should be used to delay loading of additional addons like TacO  OR
- addons should be loaded after the end of the whole account start sequence generally and also with some time delay in between to give slower CPUs some time ;D
- additional button(s) on the account picker overlay for starting addons like TacO manually
