### ISSUE TITLE
Chinese client - using custom arguments

### ISSUE THREAD

**Issue by 147172654** [TheCheatsrichter/Gw2_Launchbuddy#315]
"Custom launchargument support. This now also enables the chinese gameclient to multibox when set up with the -dat argument."
how to set...
![20220305010823947](https://user-images.githubusercontent.com/65840215/156809779-caf3db32-b17a-4e69-b27f-fc7f89324c81.jpg)
like this?

![20220305011316740](https://user-images.githubusercontent.com/65840215/156810718-e42859d6-0035-475e-a429-9962a81493e2.jpg)
but -dat can't LB....
![20220305011336180](https://user-images.githubusercontent.com/65840215/156810776-b0766697-4e09-49cb-9dd6-0dea13cbea7d.jpg)

...how to do.  THX :)

**Comment by TheCheatsrichter** [comment]
I currently dont have access to a chinese game client. Feature suggestion was however based on https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/291#event-6161726505
[lcdlyxrqy](https://github.com/lcdlyxrqy) Might be able to help you here

**Comment by lcdlyxrqy** [comment]
I believe you're using the -dat option in a wrong way. The -dat option should always be followed by a path string which is the gw2.dat file path (in the case of chinese client it's the gw2.dat directory path).
The reason why the Chinese server client need that option is that the client somehow ignores -shareArchive and still reads files in the gw2.dat folder with an exclusive sharemode (something like the `dwShareMode` argument in [the win32 CreateFileW api](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew) ). 
So you basically have two options:
1. make a duplicate copy of gw2.dat for every account you need to multi-box and pass the path of the different copies to the -dat option for different accounts. Each copy will take ~50GB extra space. This is what I currently am doing because it's simple.
2. use something like windows api hooking or some custom file system that can mirror the files(like [winfsp](https://github.com/winfsp/winfsp) or [dokany](https://github.com/dokan-dev/dokany)) to intercept the file-related api calls and modify the sharemode. This is definitely possible but I haven't looked into it closely yet. If you have some programming skill you're free to explore.
And please don't try to contact in person when it's something you should leave publicly like in a github issue. I'm not a gw2 launchbuddy maintainer so I don't check the issues here often. But you can mention me and I will see it immediately.

**Comment by 147172654** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/315#issuecomment-1062469462


我想知道，3.0加了-dat指令后是用一个客户端就能多开，还是跟以前一样需要不同的客户端才能多开？谢谢

**Comment by lcdlyxrqy** [comment]
> 

Actually it's not the login .dat file. It's the huge game data  file in the root folder of the game. For the NA/EU client -shareArchive option already does the trick for sharing the file but the Chinese client somehow failed at that. The only thing -shareArchive does for Chinese servers is that it won't occupy the login .dat file exclusively.

**Comment by lcdlyxrqy** [comment]
> [#315 (comment)](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/315#issuecomment-1062469462)
> 
> 我想知道，3.0加了-dat指令后是用一个客户端就能多开，还是跟以前一样需要不同的客户端才能多开？谢谢

@147172654 
gw2 launchbuddy never helps that issue regarding cn server clients multiboxing. If you only need a simple answer, then no, you still need "duplicate clients". If you want to understand in detail please read [#](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/315#issuecomment-1062469462) again. If you have some doubt about the content or have trouble reading english please let me know.

**Comment by 147172654** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/315#issuecomment-1062479969

Thank answer, ask again, if you still need different client same as before to the end, the new added the custom dat function is stem what of, never the dat with different clients also can open, is updated every time needs to be updated all the client once more troublesome and takes up hard disk partition with space, New functionality has been added, but it still needs a different client as before. What does the new functionality do? Thank you... Reading English by machine...

**Comment by lcdlyxrqy** [comment]
> [#315 (comment)](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/315#issuecomment-1062479969)
> 
> Thank answer, ask again, if you still need different client same as before to the end, the new added the custom dat function is stem what of, never the dat with different clients also can open, is updated every time needs to be updated all the client once more troublesome and takes up hard disk partition with space, New functionality has been added, but it still needs a different client as before. What does the new functionality do? Thank you... Reading English by machine...

@147172654 
I'll comment with both languages then. Actually I came up with #291 as a general feature request rather than a it-solves-all feature request for the cn client. The feature of customizing command line arguments is a tiny step towards multiboxing for cn clients and I think it would be a nice feature generally. The things is, it would take more effort than that if you want multiboxing to work for the cn client and I don't count on the author to work out everything for us. Keep in mind gw2 launchbuddy is originally aimed at NA/EU players. The author don't have access to cn client as well. It would be too much to ask.

我接下来会用双语评论。实际上我提出 #291 这个issue是作为一个通用的feature request而不是一个为国服客户端解决了一切问题的feature request。能够自定义命令行参数对于国服多开来说只是一小步，而且我认为这个特性总得来说总是有好处的（并不仅针对国服的情况）。实际情况是，想要让国服客户端能够多开，你需要做的事情不止这点，而且我也并不指望作者为我们解决所有事情。你要记住这个工具主要是给欧美服玩家用的。作者本身也并没有国服客户端。要求他帮我们实现国服多开显然要求太高了。

**Comment by 147172654** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/315#issuecomment-1062504809

感谢感谢，一开始我看作者写3.0能支持中文版多开，以为是跟美服一样一个客户端就能多开了，之前我只加上-dat，提示错误，再经过您的解答后发现后面要加文件路径，现在加上之后也发现了一些方便的地方，以前多开前需要手动选择不同分区里的不同客户端gw2.exe然后启动，现在把不同目录里的dat位置加入到自定义里，可以直接选择启动不用在手动选择了，虽然还是需要很多客户端，但是还是要感谢作者，感谢你

**Comment by lcdlyxrqy** [comment]
> 

@147172654 
Yes you only need to make copies of gw2.dat folders and add corresponding -dat options to every account now. No need to copy everything in the game folder.

是的你现在只需要复制gw2.dat文件夹并且在每个账号里加上相应的-dat选项就行了（放在任意地方都行）。不需要复制文件夹里的其他东西。
