### ISSUE TITLE
game instance UI does not display over GW2 game client

### ISSUE THREAD

**Issue by jacob-keller** [TheCheatsrichter/Gw2_Launchbuddy#32]
The new game instance UI doesn't stay on top of the gw2 clients. It does stay over every normal window though. I am running Windows 8

**Comment by Kaukov** [comment]
Are you running the clients in fullscreen or windowed mode?

**Comment by jacob-keller** [comment]
Fullscreen, but once I swapped to "windowed full screen" it worked fine! Thanks!

**Comment by Kaukov** [comment]
Yep, that's it!

That's how Windows works. If a game runs in fullscreen, it takes control over everything and nothing can draw over it. But windowed and windowed borderless (or windowed fullscreen) work just like any other Windows window, so that's why you can see the game instance UI then.

I hope that explained the problem you were having :)
