### ISSUE TITLE
Setup the audio device

### ISSUE THREAD

**Issue by TristisOris** [TheCheatsrichter/Gw2_Launchbuddy#344]
i configured gw2 to play audio only into headsets, but after LB launch it always set to "default" for both accounts.
can't find any options how to change that.

**Comment by Valakivi** [comment]
any workaround this? its all settings that get reset, weird thin is i got it to work with my own settings but now reverted and messed up again please help

**Comment by TheCheatsrichter** [comment]
Audio settings and some other settings sadly get stored in the local.dat file of Gw2. This file gets swapped out before each login and as soon as the game is running gets swapped back. So the error you describe happens because of the following:

This is what happens when you create a loginfile:
1. LB takes the "default" local.dat file (which includes Audio settings etc. which you used the last time when playing wihout Launchbuddy) moves it to a safe place.
2. Copies the default local.dat file to the place the gw2 is looking at. You now enter your logindata to create a "new" loginfile.
3. The new loginfile gets archived for future use.

So now you have the problem that each loginfile is essentialy a clone of the state of the default loginfile which was first used when creating the loginfiles. --> Harsh solution would be to launch GW2 normaly, set everything up the way your alts should have it, close it via ESC--> Exit to desktop. Now open up LB and create all loginfiles for your alts.
