### ISSUE TITLE
white screen when launching gw2 after the new patch (build 130014)

### ISSUE THREAD

**Issue by kililua** [TheCheatsrichter/Gw2_Launchbuddy#345]
after the login and clicked play, the loading screen goes white after the new patch build 130014

**Comment by ibuljeta** [comment]
Same here.
Unfortunately, this is most probably client issue, not launcher, but just confiirming it here if something can be done

**Comment by CerberusKCO** [comment]
agree, same problem here, some GW2 pages stay in white screens and doesn't work & other does work

**Comment by onilosmada** [comment]
Having the same issue. I can still open 1 account at a time. When attempting 2 or more simultaneously (multiboxing) the first selected account in the list will start successfully and the others will hang on a white window and go into 'Not Responding'.

**Comment by onilosmada** [comment]
I just experimented around this morning and it appears the issue is with the DX11 migration. Forcing each client to use '-dx9' argument fixes the issue!

**Comment by iwan094** [comment]
> I just experimented around this morning and it appears the issue is with the DX11 migration. Forcing each client to use '-dx9' argument fixes the issue!

Is it still working with no white screen (Not Responding)? May i know what did you tick on 'Arguments section. Thanks..

**Comment by ibuljeta** [comment]
Planned to post a follow-up on this also. At least for me -dx9 did not resolved the issue. Personal feeling was that it was happening less often, but was still happening.
Today I had first day since it started without any white screen and achieved it by starting instances in groups of 3 (was doing 5 previously) and waiting until all 3 go to either character select or SMS dialog before touching anything. If i had more than one SMS screen, I wouldn't start them all at the same time, but would go to game, collect daily and closed every one before going to next one.
Livable but not ideal.
