### ISSUE TITLE
login information are blank on random account start (50% of all my account)

### ISSUE THREAD

**Issue by Ryu-Pendragon** [TheCheatsrichter/Gw2_Launchbuddy#366]
Some random connection i got gw2 luncher to have zero login information  so the game dont start :( dont know how to solve this 

all have check remember this account and password so it weird

**Comment by Ragrug** [comment]
i have the same problem. it doesn´t matter if i use launchbuddy to start or manually start the game. it´s always a 50/50 chance the login info is blank

**Comment by ubereffect** [comment]
I'm guessing the issue is either with your login / dat files, and/or your Launchbuddy settings file Accs.xml.

Users\Your User Name\AppData\Roaming\Guild Wars 2\
Users\Your User Name\AppData\Roaming\Gw2 Launchbuddy\

The first directory noted above is where Guild Wars 2 saves your Local.dat file. The second directory is where Launchbuddy saves it's information, including the Accs.xml which holds most of it's settings. When you have Guild Wars 2 remember your login information, it stores that in your Local.dat file. Launchbuddy makes copies of this file, for each of your accounts, enabling you to login to multiple accounts. These dat file copies are saved in Launchbuddy's Loginfiles subdirectory.

While it doesn't specifically address your issue, I suspect the work arounds presented in #375 may apply here as well.
