### ISSUE TITLE
Optional: Add Backup Information -- does not work

### ISSUE THREAD

**Issue by Kenji-03** [TheCheatsrichter/Gw2_Launchbuddy#376]
**Versions:** V3.0.4 / V3.0.5 / V3.0.6

**Problem-brief:** Recreating does not work. Will enter other account info, wrong info, no info, etc. When using the recreate button and manually logging in, login will corrupt and launcher will not successfully load.

**Problem-Detailed:** When clicking the recreate login file button it often does not pull from the profile listed (very frequent), fails to enter an email (common), and puts the password in the email field (rare). Also, when it recreates the file with a blank password, entering the correct password for that account will result in the account not completing the launcher process -- leaving a  white screen and no game.

**Comment by ubereffect** [comment]
I'm guessing you've already used 'Set Loginfile' and it works or worked for a time. Also guessing you've since tried using 'Repair Loginfile' and it didn't repair your already created login file(s)?

As for the 'Optional: Add Backup information' function. I understand it to be used under very rare circumstances, where the above doesn't work. So rare that I doubt many have even set it up, I know I haven't. That being said, it's much easier for a bug to go un-noticed for a feature that's rarely ever used.

One last thing. Launchbuddy has the following text in red letters: 

> ATTENTION: Before using recreation make sure that remember email and remember password was checked on the last successful login!

I have no idea why the above is important, but apparently it is.

**Comment by ubereffect** [comment]
Just came across something that may, or may not, be related.

See #353 where users report a similar issue being resolved by turning off Windows scaling. The latest version of Launchbuddy at the time was 3.0.4, which had been out for over 3 months when this other issue was reported. Apparently still an issue with 3.0.5 and 3.0.6.

Maybe worth ensuring you have Windows scaling set to 100%?

**Comment by TheCheatsrichter** [comment]
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/383
