### ISSUE TITLE
GFX Swapping error- GFX file gets locked when map is loaded

### ISSUE THREAD

**Issue by Aleopca** [TheCheatsrichter/Gw2_Launchbuddy#377]
Mines was working flawlessly until this latest gw2 patch where everything has went wrong. (heres my crash report window for example, notice where the scroll bar is, that's how many errors i'm getting since the latest patch vs how many errors i've had in a year or so of using launch buddy)
![launch crashes](https://user-images.githubusercontent.com/47941386/188310339-2563c830-ec65-4767-a751-1526a3cecea3.png)

Had the same issues as others of having to remake every account because it couldn't update logins properly, but its "working" for the most part now.
Basically i have issues of randomly the first 5 accounts i open will not do the login delay at all sometimes, sometimes it will kick in sometimes it will just open all 5 at once, its always working for the next 5 though.

My main issue though is an absolute guaranteed error every single time, it doesn't matter if i load my alts in chunks of 3,4 or my usual 5 at a time. There will be 1 or 2 accounts that do not load with an error popping up about privelages 
![launch error](https://user-images.githubusercontent.com/47941386/188309897-15865417-bd19-4996-866c-550717e2460b.png)

This wasn't the only error, i would sometimes also get a crash report screen for 1, or an error window that looks like one of the old original gw2 launcher, i've not seen it in awhile so can't remember exactly but i think it said things about archives.

The error in the picture though, this is 100% guaranteed to happen every block of alts i load up since the issues started, it seems to ALWAYS be the second account loaded in the block, sometimes also including the third, yet the first, fourth and fifth tend to load no problem. This happens regardless of if launch buddy is launched as admin and if gw2 is launched as admin
I can get round it by waiting for every alt to load so that the game instances window will work and show me which account hasn't been loaded.
Unfortunately though, i am noticing that i'm starting to miss alts out sometimes because of this happening so often and i'm leaving accounts not logged into thinking they have been done.

The other issue i've been having is accounts seem to be totally random at times, to no rhyme or reason i've seen some of my accounts just totally change their login info in a manner that makes NO sense.
For example, i have my main account at the top so i can do alt stuff and daily stuff while the alts are loading up, but 2 days ago when i went to login to account 16, its login info had been changed to my main account? That's three 5 account blocks away from when my main is opened up so i don't get how that could be an error in copying over.
It's happened randomly with a few accounts now and it's getting hard to actually keep track of them all each day because of these issues.

**Comment by ubereffect** [comment]
> Basically i have issues of randomly the first 5 accounts i open will not do the login delay at all sometimes, sometimes it will kick in sometimes it will just open all 5 at once, its always working for the next 5 though.
> 
> My main issue though is an absolute guaranteed error every single time, it doesn't matter if i load my alts in chunks of 3,4 or my usual 5 at a time. There will be 1 or 2 accounts that do not load with an error popping up about privelages ![launch error](https://user-images.githubusercontent.com/47941386/188309897-15865417-bd19-4996-866c-550717e2460b.png)

I've gotten in the habit of launching 3 clients at a time, since months ago. That seemed to be the sweet spot for me, as I'd run into issues trying to launch 4 or more at a time. I assume this was due to login delays. If I try to launch 3 clients at a time using 3.0.6, the first 2 launch without issue. But all I get for the 3rd client is a blank screen, and if I give it a few minutes, I end up getting the following error: 'Guild Wars 2 Game Client is not responding'. I'm guessing 3.0.6 is just launching my game clients too fast.

As for the error message you're getting about insufficient privileges. That doesn't seem like an issue with Launchbuddy to me. Not sure why it would pop up for some accounts, and not others though. A simple work-around maybe to move your GW2 folder from your Program Files directory, to some other place that does not require administrator privileges

**Comment by Aleopca** [comment]
Sorry but i'm perplexed by this dismissal that it's launch buddy issue, what else is mixing up my logins? 
I paid attention to the crash screen today and its not a guild wars 2 crash report, it's launch buddy.
![it is launch buddy](https://user-images.githubusercontent.com/47941386/188482288-9307a4ad-aa19-4d90-96f7-730f6757bc76.png)

**Comment by ubereffect** [comment]
Your Windows Operating System and/or Security Software is most likely trying to protect your 'Program Files' and/or 'Program Files (x86)' directory from malware. Have you tried moving your GW2 game client from 'C:\Program Files\Guild Wars 2' to 'C:\Guild Wars 2' for example?

**Comment by Aleopca** [comment]
My gw2 folder has never been in my c drive and its actual location has the same exemptions it's always had, same goes for launch buddy folder.

**Comment by TheCheatsrichter** [comment]
Sadly couldn't find your crashreport with the matching timestamp. However I did find a very similar crashreport from somebody else which fits the description.
Gathered infos:
- This crash seems to only happen when another gameclient is allready running
- Several user crash reports had one client switching / loading map instances while launching an additional client.
- Crash originates from file access issues. Either LB can't access the GFX settings file or the Gw2 gameclient can't access them because LB currently uses them.

Theory:
- The Gw2 gameclient writes some data to the GFX file when a new map is loaded. Gw2 uses GFX file --> LB waits for file access --> gets file write acces asap because the file got "closed" by the Gw2 client --> Gw2 gameclient trys to open GFX file again for some reason. In this case whoever is faster gets the file access and crashes the other software.

Solution / Next Steps:
- I have to check if the Gw2 Gameclient is happy with FileShare Modes.
- Additional testing has to be done. When does the GFX get used by the Gw2 gameclient AFTER the character screen.
- 3.0.7 ( currently patreon exclusive ) allready has a additional file access flag for the GFX file which should minimize this error. However this is not a clean solution!

**Comment by Aleopca** [comment]
I didn't hit submit until a few minutes later so it won't appear with the timestamp of the picture exactly.

Theory sounds good to start with but unfortunately i doubt it's that, it happens regardless of if any account is actually signed in,  the accounts don't have authenticators so i often have to manually select skip authenticator before the gw2 client will even fully boot up, still get these errors.

Prior to all the issues coming from the latest patch i would be logged in on 1 account logging into many alt chars doing jumping puzzle chests and stuff while the alt accounts load up, never had any of these errors. It's all only started since the latest gw2 patch and having to redo every account when launch buddy wouldn't update them properly.

(for instance, account 3 crashed with no crash report to give before account 1 had went passed the authenticator part just now, i deliberately didn't load my main to do the usual stuff to test your theory) and accounts 2 and 4 both gave the privilege error, 1 and 5 booted up no problem.

**Comment by TheCheatsrichter** [comment]
Let my new analyse tool scan for GFX file read / write accesses:
GFX file gets edited at:
- Process start, right before the loginwindow is even possible.
- When the "Play" button is pressed at the login window
- Right before the last module for the char selection screen is loaded
- When the gameclient gets closed

These accesses are all really short (usually about 50 ms) so the IORepeater (max timeout 20 secs) shouldn't have a problem with them. Could you please go to the LB crashes tab, select the latest crash and scroll all the way down to "*--> Error Logs <--*" and post a screenshot of that?

**Comment by Aleopca** [comment]
If it counts for process start then your theory definitely looks more promising, figured that required the client to be loaded.
For clarity about finding the crash report earlier, i'm noticing on these error logs that the time stated in the error log is 1 hour earlier than the actual crash, the correct times are stated in the crash logs window but 1 hour earlier in the info log. It's showing 15:xx rather than 16:xx, crash report looked to be correctly reporting 16:xx but might show 15:xx on your side.

The errors tend to be similar but differ in size so i've included a few. These are from yesterday.
![error log 1](https://user-images.githubusercontent.com/47941386/189477286-7f5c23f9-98a5-41ce-bf12-0d8fd26497f0.png)
![error log 2](https://user-images.githubusercontent.com/47941386/189477288-9e7e6db9-76c9-4196-a51d-aec44339b7b5.png)
![error log 3png](https://user-images.githubusercontent.com/47941386/189477289-f3c6c781-0d9e-4c33-bee6-935644e3283f.png)
![error log 5](https://user-images.githubusercontent.com/47941386/189477290-42524d2d-d22c-4f0a-8c09-52a31c9a8a1b.png)


and this one is from the day where the first 10 accounts loaded perfectly fine, but once i got to 11-15 and 15-20 the issues came back 
![error log 6](https://user-images.githubusercontent.com/47941386/189477342-8b9c5e27-eab7-4549-8b4a-ce60dab8cd51.png)
