### ISSUE TITLE
download failed in many of my alts, after this update on the 14th

### ISSUE THREAD

**Issue by laroxyz** [TheCheatsrichter/Gw2_Launchbuddy#379]
I'm having trouble logging into many of my accounts, I'm completely new to the subject so I don't know what to do
few/almost not even one of my accounts opens it simply appears download failed! help me
![download failed!](https://user-images.githubusercontent.com/113496363/190065582-2f986d3d-913a-4426-81c7-14802c820b41.png)

**Comment by Koraydi** [comment]
I am also having this same issue

**Comment by TheCheatsrichter** [comment]
Updating several accounts quickly one after another can result in DDOS protection triggers on Anets servers. Workarround would be to enable a VPN or wait for some time for the DDOS protection to wear off.
I am currently investigating timings to implement some counter measurements.

**Comment by laroxyz** [comment]
today I tried to enter the accounts again, still with the same error even after 24 hours have passed, I will wait another day

**Comment by PaRTWasTaken** [comment]
I had a couple of accounts stuck with the same issue, making a new login file fixed the issue. It could be that whatever's going wrong is corrupting the login file and that's what is causing the error... then again I'm no expert. Try it, maybe it works for you too :)

**Comment by laroxyz** [comment]
> I had a couple of accounts stuck with the same issue, making a new login file fixed the issue. It could be that whatever's going wrong is corrupting the login file and that's what is causing the error... then again I'm no expert. Try it, maybe it works for you too :)
it really worked, it's a little frustrating to miss a few days of logging in I really have a lot of accounts, I should pay more attention and use vpn every patch notes

**Comment by AEsylum** [comment]
> I'm having trouble logging into many of my accounts, I'm completely new to the subject so I don't know what to do few/almost not even one of my accounts opens it simply appears download failed! help me ![download failed!](https://user-images.githubusercontent.com/113496363/190065582-2f986d3d-913a-4426-81c7-14802c820b41.png)

Hi, you can fix this by going into "Account Settings" on the left, select one account, expand the "Login Credentials" section, then click on "Repair Loginfile" and repeat this for each account you have set up.

I'm also frustrated that I have to manually do this each time GW2 has an update. Hopefully the cheatsrichter fixes this soon.

**Comment by Nodzzzzz** [comment]
One fix me and my friend has done because the "Repair Loginfile" option does not work for both of us is whenever the error occurs we immediately close GW2's client then reopen it from the original launcher and not from launchbuddy's.

Attached is how the process is done.
![2022-09-16 13-26-17](https://user-images.githubusercontent.com/113660844/190563559-828c3b1c-2abc-4f84-9970-df5de138af55.gif)

**Comment by accelleratii** [comment]
> Updating several accounts quickly one after another can result in DDOS protection triggers on Anets servers.

Does not update happen before logging in? We are just refreshing multiple .dat files on LB start. Once we select multiple accounts in LB to launch, given we updated the game manually before, there should be no download required.

**Comment by jazdarc** [comment]
I'm having this same issue.
The 'repair login file' option doesn't work for me also. I can't get it to work on any account.
I rolled back the launch buddy version to the previous one that I didn't have issues with, and the issue is still happening.
In the meantime, I'm also doing the work around Nodzzzzz is doing above.

**Comment by maconho** [comment]
This problem is also happening with me.
Have 100 accounts here. Every time the game updates LB auto update all the launchers on LB start, but all the launchers get broken and I need to fix all the 100 accounts manually on "Repair Loginfile" button. 
It took me arround 25 minutes to wait the auto update, plus more 30 minutes to manually update all the accounts. So arround 1 hour of waiting before can be able to login the first account.

It's not a huge problem when the game update 1 time every 2 weeks, but man, this last week Anet launches micro updates almost everyday and the process need to be done alot of times.

**Comment by Alimar777** [comment]
Have this issue too. Not sure what happened as I never had an issue until the most recent launchbuddy update. It seems using 2.4.2 to update my login files works as a stopgap but only if the current version doesn't touch them first.

**Comment by jazdarc** [comment]
If it helps, I've also found that the repair login file feature seems to fix it, BUT you have to press the repair the login file button multiple times on the same account until you notice that it doesn't download anything anymore. 
On some accounts it's taken up to 10 clicks of the 'repair longin file' button. 
BUT after this, it all works completely as normal. HOORAH!
That is until Arenanet rolls out another game update, then I have to redo the above again which you would think only one press of the repair login file, but no it's multiple presses again. Still way better than manually doing it, so thank you thank you thank you! :D <3

**Comment by Alimar777** [comment]
> If it helps, I've also found that the repair login file feature seems to fix it, BUT you have to press the repair the login file button multiple times on the same account until you notice that it doesn't download anything anymore. On some accounts it's taken up to 10 clicks of the 'repair longin file' button. BUT after this, it all works completely as normal. HOORAH! That is until Arenanet rolls out another game update, then I have to redo the above again which you would think only one press of the repair login file, but no it's multiple presses again. Still way better than manually doing it, so thank you thank you thank you! :D <3

If I'm not an idiot and start updating before I realize. I can usually update with 2.4.2 to avoid the problem. However it would be nice to have a mass "repair all logins" button instead of having to do it one by one.
