### ISSUE TITLE
v.3.1.0 alpha automatically opening gw2 news page after login

### ISSUE THREAD

**Issue by luzclasil** [TheCheatsrichter/Gw2_Launchbuddy#394]
I did not like this new feature implemented in 3.1.0 and I'd like to disable it if I can.
However after checking all settings I did not find and option to disable it. Am I missing something?
Not fun to have multiple tab wasting resources and having to manually close them when you login 5 accs at a time, 40 a day
Ty!!

ps: at least for me it's [this page](https://www.guildwars2.com/en/news/black-friday-deals-discounts-on-guild-wars-2-expansions/) it's opening

**Comment by Windfreeze1** [comment]
It's doing the same for me.

**Comment by luzclasil** [comment]
> It's doing the same for me.

I was trying to troubleshoot this problem so I could give more info about it and apparently it has something to do with "Press gameclient login button on gamestart". If this option is not ticked then it won't open the news page.

If "Press gameclient login button on gamestart" is ticked, I have the feeling that launchbuddy is auto clicking twice. Once at login button and a second time at the banner that appears at the same place when you login successfully. And this is what is redirecting to gw2 news page.

So I do think we're talking about a possible bug and not a feature that was implemented on purpose.

**Comment by ScrambledBrain** [comment]
Same issue for me on german client.
It is good to see, that my wish to skip 2FA reminder is implemented, but the mouse clicking feature maybe really double clicks at 2FA/Login area or is not yet ready for other language UI sizings or something like that.

**Comment by TheCheatsrichter** [comment]
Setting can be disabled here 
![image](https://user-images.githubusercontent.com/15090699/202873289-1681b9f6-7d5e-4665-b173-60a29816c558.png)

Currently working on language detection so I can press buttons accordingly. Workarround would be to use anything other than the "none" authentication type in the account settings.

**Comment by TheCheatsrichter** [comment]
Fixed in the next release ;)

**Comment by ScrambledBrain** [comment]
>Fixed in the next release ;)

Sounds better than disabling "Press gameclient 'Login Button' on gamestart" completely, because that's the reason we use GW2LB ;D

This news page opening drives me crazy ... but it is not always happening ... strange behaviour.
Hopefully the new version is coming soon to github ;)

--

For the 2FA topic:
I realized, that not only SMS is a 2FA possibility but also an time based authenticator.
Using such an authenticator app does not need personal phone numbers for 2FA.
Additionally ArenaNet also gives the possibility to save your current network where you come from.
Now I don't have that nasty 2FA reminder anymore for my accounts :D

**Comment by WolfSabian** [comment]
Ya. I've had the odd one opening up from time to time but just had the news page open up in 8 browser tabs while logging in 1 account
