### ISSUE TITLE
Launchbuddy forgets account data, saves up wrong account data or doesnt progress after successful login

### ISSUE THREAD

**Issue by Flauschedrache** [TheCheatsrichter/Gw2_Launchbuddy#415]
My gw2 launchbuddy acts strange lately I have one of the 3 problems all the time.

- gw2 lb doesnt remember my email adress, window starts with a blank field
- gw2 lb saves up the wrong account data. Sometimes after a sucessful login, the next login get me the text that my password is wrong (email is correct tho)
- gw2 lb doesnt progress after a succussful login, the window just stands there. When I press gamestart or close the window, gw2 lb says that something went wrong with the login try.

One important note, the only thing I changed is that I have a seperate account for my user and admin. So the admin privilege uses another account on my computer. I tried copieing the appdata from my personal account to my admin account. Reinstalling and trying to get it from new results in the said problems.

**Comment by TheCheatsrichter** [comment]
Sadly I only give you some information on how the upcoming version will fix some of these problems:

> * gw2 lb doesnt remember my email adress, window starts with a blank field
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/383 a bug introduced by anet in the gw2 client therefore nto directly fixable. The upcoming version 4.0 will have a workaround implemented

> * gw2 lb saves up the wrong account data. Sometimes after a sucessful login, the next login get me the text that my password is wrong (email is correct tho)
This could be caused by a slow saving speed of the loginfile. Do you run gw2 on an old and slow HDD?

> * gw2 lb doesnt progress after a succussful login, the window just stands there. When I press gamestart or close the window, gw2 lb says that something went wrong with the login try.

4.0 improved in a big way regarding automated logins. Please be patient for the public release. Closed alpha is currently running at patreon.

> One important note, the only thing I changed is that I have a seperate account for my user and admin. So the admin privilege uses another account on my computer. I tried copieing the appdata from my personal account to my admin account. Reinstalling and trying to get it from new results in the said problems.

I personally haven't tested this but it could be possible that the loginfiles are encrypted by a user based key. This means copying them over to a other user / machine might makes some data invalid ( my guess is password ). Could you try copying it back to the old user and see if the login works again?

**Comment by Flauschedrache** [comment]
Hey thanks for answering!

> This could be caused by a slow saving speed of the loginfile. Do you run gw2 on an old and slow HDD?

I muss an SSD (M2) so speed shouldnt be a problem.

> I personally haven't tested this but it could be possible that the loginfiles are encrypted with a user based key. This means copying them over to a other user / machine might makes some data invalid ( my guess is password ). Could you try copying it back to the old user and see if the login works again? Keep in mind that the loginfile should not be launched onces on the other user as an invalid login will overwrite the loginfile.

I did exactly that, the vanishing email made it a bit difficult, so I added the email quickly before the launcher tries to login to see if the password is correct and you are right, it seems copieing the file to another isnt possible since like you said its encrypted. But it worked when copieing it back to the original.


So I think waiting for your workaround with the email and doing the logins anew with the new user would fix most of my problems.
