### ISSUE TITLE
Needs heavy updating - Doesnt work currently.

### ISSUE THREAD

**Issue by Remwulf** [TheCheatsrichter/Gw2_Launchbuddy#429]
Doesnt work to launch multiple accounts anymore after GW update of 18-04-2023,

Aswell needs options to hide the very annoying UI popup's that come up with "waiting for launch / updates" They're a nuisance and shouldnt be there.

**Comment by Qwix005** [comment]
WORKAROUND:   I went here https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases  grabbed V3.0.3.  I put it where my launchbuddy is, and put the newest version in a storage folder.  Later when it gets fixed, I can reverse the process.  (The older version takes longer to update the login file, but is working)

**Comment by Zodiaksl** [comment]
> WORKAROUND: I went here https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases grabbed V3.0.3. I put it where my launchbuddy is, and put the newest version in a storage folder. Later when it gets fixed, I can reverse the process. (The older version takes longer to update the login file, but is working)

Hello,

Since Gw2 Launchbuddy is its own self containted .exe with no additional files containing your account info, how do you get around having to re-enter all of your multiple account's worth of login info, settings, etc when reverting from current version to 3.0.3 and back again?

I'm wanting to do this but dread the thought of having to redo all 9 of my accounts.
