### ISSUE TITLE
3.2.5 Auto Login Issue?

### ISSUE THREAD

**Issue by WolfSabian** [TheCheatsrichter/Gw2_Launchbuddy#431]
Got the new 3.2.5 build which i'm very happy to see released.

However for me when i log in an account the "Powered by Launchbuddy" progression bar gets to 40% and disappears, then it sits there at the username/password screen without progressing further unless I manually click login and ready.

This happening to anyone else?

**Comment by Fribb** [comment]
Can confirm, this is happening to me too.

**Comment by Vatrez69** [comment]
I have the same problem

**Comment by WolfSabian** [comment]
Glad it's not just me.  Hopefully a fix soon.

**Comment by rolsk** [comment]
>Further bugfixes etc. will be included in the upcoming 4.# release, which is currently in open Beta phase at patreon.

Seems like there is a financial incentive not to fix it.

**Comment by roggstudelpest** [comment]
+1

**Comment by Tristan-Louvre** [comment]
Instead of calling someone out for getting probably negligible money for providing their time and energy to create something the vast majority of us use for *free* try reading carefully. It is in Beta on Patreon and will come out when he (with full right) decides that it is worth dropping. Your entitlement is a you problem. Stop projecting.

**Comment by ManniMan** [comment]
There was a workaround with the argument -usecoherent. Since this argument was removed from GW2 game client with the July, 18th update, that workaround is gone now. Seems like the manual press on login button is the only way other than subscribing to the beta version via Patreon.

There is a duplicate issue open as well: https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/434

**Comment by WolfSabian** [comment]
> There was a workaround with the argument -usecoherent. Since this argument was removed from GW2 game client with the July, 18th update, that workaround is gone now. Seems like the manual press on login button is the only way other than subscribing to the beta version via Patreon.
> 
> There is a duplicate issue open as well: https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/434

Nah this has nothing to do with coherent or chromium. Most of my accounts were being forced to use coherent due to an issue between chromium and add-on manager. And it was still an issue

**Comment by ManniMan** [comment]
> 

At least it worked for me since chromium was introduced and it doesn´t work anymore since Tuesday (with the same Version of GW2 Launchbody).

**Comment by Fribb** [comment]
It has now been 5 months since this was reported, when will this get fixed?
