### ISSUE TITLE
Not working correctly on linux

### ISSUE THREAD

**Issue by SoulInfernoDE** [TheCheatsrichter/Gw2_Launchbuddy#454]
**Describe the bug**
Opens but functions are not working..

**To Reproduce**
Open/execute launchbuddy under linux with lutris

**Expected behavior**
Just to work out of the box like 99% of any games and apps now working like that.

**First happend in LB Version**
Issue first appeared in LB Version : newest

**Comment by Lukaboot** [comment]
have you considered that this uses windows functions to spawn the multiple clients? what a weird thing to assume linux people have

**Comment by Kaukov** [comment]
There's a trick with Lutris. After you've installed GW2, you can copy the directory multiple times, then "install" GW2 over and over again, but after it's done, point it to the copied directory. That way you can have many accounts that have their own prefixes and don't interfere with one another. No need for Launchbuddy.

**Comment by SoulInfernoDE** [comment]
Thanks for the hint. Do you know if this needs more system resources than using it with launch buddy?

@Lukaboot GW2 is using windows functions, so no point.

best regards

**Comment by Kaukov** [comment]
It actually uses less resources because you're not running another process that's taking up memory and CPU. You're just running multiple GW2 instances. You just need more disk space because you're essentially copying the whole prefix which already has a lot of stuff in it.

I've been running like this for 5 years now without any issues. GW2 is installed in a separate directory where all my games are, and the lutris prefixes are all inside a `gw2` directory for better maintainability. And in Lutris I just rename the "game" so I know which account I'm launching.

**Comment by SoulInfernoDE** [comment]
Very every nice, thank you so much ❤️
