### ISSUE TITLE
1.4.2 can't multibox 80% of the time

### ISSUE THREAD

**Issue by foodbandlt** [TheCheatsrichter/Gw2_Launchbuddy#52]
Just like #33 , getting this error about 80% of the time.  Sometimes it works randomly, though no changes have been made.  Could this be because the -shareArchive option is not set when starting gw2-64.exe?  On the troubleshooter after this message it lists the command line options used and that one isn't present.

**Comment by KairuByte** [comment]
That would indeed be the problem, but it's odd because that flag is always set unless you run specific troubleshooting processes or the update. It's a "non optional" command line argument in LB. 

Unless you are attempting to run the code in the refactor branch, which is in a state of flux. I believe it's a known issue in current refactor branch, but I've been tending to family matters this past week and a bit, so haven't had a chance to properly finish and push the latest version on my system.

**Comment by foodbandlt** [comment]
That's what I assumed it should be.  I'm running the binary from the 1.4.2 release published on here.  I did run the troubleshooting process once in the past, maybe something got stuck?  I'll rerun it and see if it gets unstuck by some miracle, heh.

**Comment by foodbandlt** [comment]
I just nailed down what the symptoms seem to be.  It only seems to fail when the client isn't updated initially.  It will ask if you want to update, which I hit yes on until the client no longer downloads anything, though it will keep asking you.  If you keep hitting yes it will ask you perpetually.  If you hit no, it will list the client is outdated (which it isn't at this point).

The fix is to restart LB.  This, I assume, causes it to re-check the client build and see that it is actually updated.  This was a large problem recently because they've been patching almost every day, and I haven't been restarting LB after patching.  Perhaps it needs to check the build number before prompting for update again, or something related to that is broken.

**Comment by KairuByte** [comment]
The update process is on my list of things to handle. Unfortunately there's no concrete way to handle the client updating, but we can definitely handle the process better.

**Comment by midnights-straychild** [comment]
I had a similiar problem. But after a while of trying wild things, I saw a lot of emails with codes to confirm the new network. Is there a way to disable that?

**Comment by KairuByte** [comment]
There is currently no way for LB to handle 2 factor of any type. The exception being that you have previously trusted your current network.

I am looking into options to handle these situations, but the likeliness is quite low.

**Comment by sumphatguy** [comment]
Hi. I am currently having this issue and am not sure why. Sometimes, the accounts do not multibox at all. Sometimes the accounts skip over the ones in the list (so accounts 1, 2, and 4 launch, even though 1 through 4 were all selected). Sometimes, only one account launches at a time. Lately I haven't been able to use the multiboxing feature effectively at all.

**Comment by KairuByte** [comment]
I'm actually working on that in the refactor branch. Instead of trying to deal with timings and the like, we simply retry until things work properly.

That said, it's not perfect. I'm not certain we are ever going to get that process down perfect and I may need to just add a delay option for people to use when this problem is run into. 

I believe the problem is tied to the specs of the machine running LB, but unfortunately I don't have much in the way of low end to test with. I have thought of spinning up a "worst cast" VM to test on but I've been more focused on making the code more modular and organized. Hopefully when I have the time to test with a VM I'll be able to figure something out.

**Comment by KairuByte** [comment]
So 1.7 uses a scaling value for delay. It will wait an increasingly larger amount of time between retries, ending on the 10th retry 10 seconds after the 9th.

If that still doesnt work, latest has a --delaymutex flag that takes time in ms to wait between attempts. I wouldn't suggest any larger than 10 seconds though, and keep in mind that LB will essentially be frozen waiting for the mutex to successfully close. It does still attempt the close 10 times.

**Comment by TheCheatsrichter** [comment]
Closed because of mutliple code overhauls.
