### ISSUE TITLE
Domain in local-part of the email.

### ISSUE THREAD

**Issue by HerrDepence** [TheCheatsrichter/Gw2_Launchbuddy#55]
I can't add an Account to the Manger with an domain in his Email. (Example: google.com@guildwars2.com)
It says thats an "Invalid Email!".

EDIT: I have the newest version (V1.4.2)

**Comment by KairuByte** [comment]
I haven't looked at that piece of code in particular... I wonder if there's a regex involved, which would cause the weirdness.

I'm not actually certain that it makes sense to check it at all to be honest, since the worst that will happen is a user will not be able to log in. I might just remove it completely from the next version...

I can push the fix into the refactor branch pretty easily, do you have the ability to compile it? There are also some other potential problems with the refactor branch that I have not worked through yet.

**Comment by HerrDepence** [comment]
Sure, i'll try it and report back.

**Comment by KairuByte** [comment]
I'm not sure when this got fixed, but it appears to be working in at least the refactor branch. Looking through the code... I'm not sure why this wouldn't have worked previously.

If you are still having troubles, it's not to do with the domain in the name.
