### ISSUE TITLE
Multiple problems when Guild Wars 2 client has never been run

### ISSUE THREAD

**Issue by KairuByte** [TheCheatsrichter/Gw2_Launchbuddy#9]
While debugging mutex code I started the application under a user account that has never used the client before. Multiple exceptions ensued. Better handling of first ever run should be on the list of things to do.

(I can likely handle this eventually but I'm looking for existing mutex problems that will effect most people)

**Comment by ShiftLeftLogical** [comment]
I closed issue #82 because I could not reproduce but I would not at ALL be surprised if these two issues are related as this was the state my user account was in when hitting the issue where 0 handles were found for GW2.exe when trying to kill the mutex.

I will create some new user accounts and try to reproduce #82.

@TheCheatsrichter - Is there an easy way to get rid of ANY/ALL LB user/machine data such that LB will reinitialize all configuration files / registry values or is it as simple as just removing the AppData for the user?

**Comment by TheCheatsrichter** [comment]
@ShiftLeftLogical 
There are 3 files/folders to delete for a fresh start:

%userprofile%\appdata\local\TheCheatsrichter
%appdata%\Guild Wars 2\Launchbuddy.bin
%appdata%\Gw2 Launchbuddy\
